name: Delete Old Branches

on:
  schedule:
    - cron: '10 16 * * *'  # Runs every day at 11:10 AM EST (4:10 PM UTC)
  workflow_dispatch:

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Delete old feature and bugfix branches
        run: |
          # Specify prefixes for branches to be deleted
          prefixes=("feature/" "bugfix/")

          branches=$(git branch -r | grep -E "${prefixes[0]}|${prefixes[1]}" | sed 's/origin\///')

          # Log all branches found
          echo "Branches matching prefixes: $branches"

          for prefix in "${prefixes[@]}"; do
            # Get the list of branches that match the prefix
            # branches=$(git branch -r | grep "$prefix" | sed 's/origin\///')

            for branch in $branches; do
              echo "Deleting branch: $branch"
              git push origin --delete "$branch"
            done
          done
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
