name: Update README

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      pat_token: ${{ secrets.PAT_TOKEN }} # Pass the secret here as input