name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get GitHub username and email
        id: user_info
        run: |
          echo "GITHUB_USERNAME=${{ github.actor }}" >> $GITHUB_ENV
          git_email=$(git log -1 --pretty=format:'%ae')
          echo "GITHUB_EMAIL=$git_email" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name $GITHUB_USERNAME
          git config user.email $GITHUB_EMAIL

      - name: Add line to README
        run: |
          echo "hello" >> README.md
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Add 'hello' to README.md"
          git push
