
name: Reusable workflow

on:
  workflow_call:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.PAT_TOKEN }}" # Use the input directly here
