
name: Reusable workflow

on:
  workflow_call:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
        
      - name: Update LINE_COVERAGE variable
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # GitHub automatically provides this secret
        run: |
          gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/BrandonWong22/workflow-test-push-to-main/actions/variables/LINE_COVERAGE \
          -f "name=LINE_COVERAGE" -f "value=120"
  

    # steps:
    #   - uses: actions/checkout@v4
    #   - run: |
    #         gh variable list
    #         gh variable set LINE_COVERAGE --body 100
    #         gh variable list
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   # with:
      #   #   token: ${{ secrets.PAT_TOKEN }} # Use the input directly here

      # - name: Install GitHub CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y gh

      # - name: Authenticate GitHub CLI
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # - name: Update LINE_COVERAGE Variable
      #   run: gh variable set LINE_COVERAGE --body 100



      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ secrets.PAT_TOKEN }} # Use the input directly here

      # - name: Get GitHub username and email
      #   id: user_info
      #   run: |
      #     echo "GITHUB_USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      #     git_email=$(git log -1 --pretty=format:'%ae')
      #     echo "GITHUB_EMAIL=$git_email" >> $GITHUB_ENV

      # - name: Configure Git
      #   run: |
      #     git config user.name $GITHUB_USERNAME
      #     git config user.email $GITHUB_EMAIL

      # - name: Add line to README
      #   run: |
      #     git pull
      #     echo "hello" >> README.md
      #     git add README.md
      #     git commit -m "Add 'hello' to README.md"
      #     git push origin HEAD:main
